### ISSUE TITLE
Issue while game is loading

### ISSUE THREAD

**Issue by sergjack2015** [klyte45/AddressesMod#33]
While game is loading, this error appears in the output log. It doesnt seem to have any effect in-game.

```
Ask at Klyte45's GitHub to fix this. Stacktrace:
   at System.Environment.get_StackTrace()
   at Klyte.Commons.Interfaces.BasicIUserModSimplified`2[[Klyte.Addresses.AddressesMod, KlyteAddresses, Version=3.1.0.1, Culture=neutral, PublicKeyToken=null],[Klyte.Addresses.AdrController, KlyteAddresses, Version=3.1.0.1, Culture=neutral, PublicKeyToken=null]].get_Controller()
   at Klyte.Addresses.ModShared.AdrFacade.get_Instance()
   at Klyte.Addresses.ModShared.AdrFacade.TriggerDistrictChanged()
   at DistrictManager.DistrictManager.AreaModified_Patch2(.DistrictManager , Int32 , Int32 , Int32 , Int32 , Boolean )
   at DistrictManager+Data.AfterDeserialize(ColossalFramework.IO.DataSerializer s)
   at ColossalFramework.IO.DataSerializer.Deserialize(System.IO.Stream stream, Mode mode, ColossalFramework.IO.LegacyResolverHandler customResolver)
   at ColossalFramework.IO.DataSerializer.Deserialize(System.IO.Stream stream, Mode mode)
   at LoadingManager+<LoadSimulationData>c__IteratorB.MoveNext()
   at AsyncTask.Execute()
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()
```
[output_log.txt](https://github.com/klyte45/AddressesMod/files/7776078/output_log.txt)

**Comment by klyte45** [comment]
Please ignore it, it's just a note to myself to fix this when I get time, but it's not relevant at all.
